//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remake_Simulator_Csharp.Scripts {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScriptsZh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScriptsZh_CN() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Remake_Simulator_Csharp.Scripts.ScriptsZh_CN", typeof(ScriptsZh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 这是个测试！ 的本地化字符串。
        /// </summary>
        internal static string achievementDescription0 {
            get {
                return ResourceManager.GetString("achievementDescription0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第一次开始游戏 的本地化字符串。
        /// </summary>
        internal static string achievementDescription1 {
            get {
                return ResourceManager.GetString("achievementDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试成就 的本地化字符串。
        /// </summary>
        internal static string achievementName0 {
            get {
                return ResourceManager.GetString("achievementName0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hello World! 的本地化字符串。
        /// </summary>
        internal static string achievementName1 {
            get {
                return ResourceManager.GetString("achievementName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这年的冬天格外寒冷,风雪拍打着门窗... 的本地化字符串。
        /// </summary>
        internal static string eventDescription0 {
            get {
                return ResourceManager.GetString("eventDescription0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 父母正领着你出门，一辆失控的泥头车忽然向你冲来... 的本地化字符串。
        /// </summary>
        internal static string eventDescription1 {
            get {
                return ResourceManager.GetString("eventDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你坐在家中阅读今天的报纸， 的本地化字符串。
        /// </summary>
        internal static string eventDescription10 {
            get {
                return ResourceManager.GetString("eventDescription10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你和隔壁的二狗撒尿和泥巴，玩的很开心 的本地化字符串。
        /// </summary>
        internal static string eventDescription2 {
            get {
                return ResourceManager.GetString("eventDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你被父母强迫在家读书 的本地化字符串。
        /// </summary>
        internal static string eventDescription3 {
            get {
                return ResourceManager.GetString("eventDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你借着和煦的春风放飞了手中的纸鸢 的本地化字符串。
        /// </summary>
        internal static string eventDescription4 {
            get {
                return ResourceManager.GetString("eventDescription4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 父母正领着你出门，一辆失控的马车忽然向你冲来... 的本地化字符串。
        /// </summary>
        internal static string eventDescription5 {
            get {
                return ResourceManager.GetString("eventDescription5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你已经到了该上小学的年龄，父母带你来到了一所崭新的学校... 的本地化字符串。
        /// </summary>
        internal static string eventDescription6 {
            get {
                return ResourceManager.GetString("eventDescription6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你已经到了该上小学的年龄，父母带你来到了一所破旧的学校... 的本地化字符串。
        /// </summary>
        internal static string eventDescription7 {
            get {
                return ResourceManager.GetString("eventDescription7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你已经到了该上小学的年龄，父母带你来到了一所学校，你很担心同学们发现你的身体和别人不同 的本地化字符串。
        /// </summary>
        internal static string eventDescription8 {
            get {
                return ResourceManager.GetString("eventDescription8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你坐在家里的沙发上看电视， 的本地化字符串。
        /// </summary>
        internal static string eventDescription9 {
            get {
                return ResourceManager.GetString("eventDescription9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 夭折 的本地化字符串。
        /// </summary>
        internal static string eventName0 {
            get {
                return ResourceManager.GetString("eventName0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车祸 的本地化字符串。
        /// </summary>
        internal static string eventName1 {
            get {
                return ResourceManager.GetString("eventName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 闲暇时光：报纸 的本地化字符串。
        /// </summary>
        internal static string eventName10 {
            get {
                return ResourceManager.GetString("eventName10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 儿时玩乐 的本地化字符串。
        /// </summary>
        internal static string eventName2 {
            get {
                return ResourceManager.GetString("eventName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读书 的本地化字符串。
        /// </summary>
        internal static string eventName3 {
            get {
                return ResourceManager.GetString("eventName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 风筝 的本地化字符串。
        /// </summary>
        internal static string eventName4 {
            get {
                return ResourceManager.GetString("eventName4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车(?)祸 的本地化字符串。
        /// </summary>
        internal static string eventName5 {
            get {
                return ResourceManager.GetString("eventName5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入学 的本地化字符串。
        /// </summary>
        internal static string eventName6 {
            get {
                return ResourceManager.GetString("eventName6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入学：破旧的学校 的本地化字符串。
        /// </summary>
        internal static string eventName7 {
            get {
                return ResourceManager.GetString("eventName7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入学：身体的秘密 的本地化字符串。
        /// </summary>
        internal static string eventName8 {
            get {
                return ResourceManager.GetString("eventName8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 闲暇时光：新闻 的本地化字符串。
        /// </summary>
        internal static string eventName9 {
            get {
                return ResourceManager.GetString("eventName9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 身体强壮的你根本不在乎这点寒冷，春天再度来临... 的本地化字符串。
        /// </summary>
        internal static string eventResult0_0 {
            get {
                return ResourceManager.GetString("eventResult0-0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 体弱的你生了一场大病，幸运的是你很快康复了，春天再度来临... 的本地化字符串。
        /// </summary>
        internal static string eventResult0_1 {
            get {
                return ResourceManager.GetString("eventResult0-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 体弱的你生了一场大病，在一个漆黑的夜里离开了这个世界... 的本地化字符串。
        /// </summary>
        internal static string eventResult0_2 {
            get {
                return ResourceManager.GetString("eventResult0-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 体质超群的你轻轻一跃便闪到了一旁 的本地化字符串。
        /// </summary>
        internal static string eventResult1_0 {
            get {
                return ResourceManager.GetString("eventResult1-0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 幸运的是，泥头车司机在最后时刻重新控制了车辆，在你面前停了下来 的本地化字符串。
        /// </summary>
        internal static string eventResult1_1 {
            get {
                return ResourceManager.GetString("eventResult1-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你没能躲开泥头车的撞击，你再次睁开眼睛的时候已经到了异世界... 的本地化字符串。
        /// </summary>
        internal static string eventResult1_2 {
            get {
                return ResourceManager.GetString("eventResult1-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在你绝望的瞬间，一股柔和的光芒将你包裹，泥头车呼啸而过，你却毫发无损 的本地化字符串。
        /// </summary>
        internal static string eventResult1_3 {
            get {
                return ResourceManager.GetString("eventResult1-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 然而你并看不懂报纸上密密麻麻的字 的本地化字符串。
        /// </summary>
        internal static string eventResult10_0 {
            get {
                return ResourceManager.GetString("eventResult10-0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ...今年却有所不同，你不再学习那些单调晦涩的文章，你感到十分快乐，父母却有些忧心忡忡 的本地化字符串。
        /// </summary>
        internal static string eventResult3_0 {
            get {
                return ResourceManager.GetString("eventResult3-0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 体质超群的你轻轻一跃便闪到了一旁 的本地化字符串。
        /// </summary>
        internal static string eventResult5_0 {
            get {
                return ResourceManager.GetString("eventResult5-0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 幸运的是，车夫在最后时刻重新控制了马匹，在你面前停了下来 的本地化字符串。
        /// </summary>
        internal static string eventResult5_1 {
            get {
                return ResourceManager.GetString("eventResult5-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你没能躲开马车的撞击，你再次睁开眼睛的时候已经到了异世界... 的本地化字符串。
        /// </summary>
        internal static string eventResult5_2 {
            get {
                return ResourceManager.GetString("eventResult5-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在你绝望的瞬间，一股柔和的光芒将你包裹，马车呼啸而过，你却毫发无损 的本地化字符串。
        /// </summary>
        internal static string eventResult5_3 {
            get {
                return ResourceManager.GetString("eventResult5-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 智力超乎常人的你轻松成为了同学们的偶像，你感到十分快乐 的本地化字符串。
        /// </summary>
        internal static string eventResult6_0 {
            get {
                return ResourceManager.GetString("eventResult6-0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 虽然你看不懂试卷上的题目，但你却总能猜中答案，这使你感到十分庆幸 的本地化字符串。
        /// </summary>
        internal static string eventResult6_1 {
            get {
                return ResourceManager.GetString("eventResult6-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string eventResult6_2 {
            get {
                return ResourceManager.GetString("eventResult6-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 智力超乎常人的你轻松成为了同学们的偶像，你感到十分快乐 的本地化字符串。
        /// </summary>
        internal static string eventResult7_0 {
            get {
                return ResourceManager.GetString("eventResult7-0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 虽然你看不懂试卷上的题目，但你却总能猜中答案，这使你感到十分庆幸 的本地化字符串。
        /// </summary>
        internal static string eventResult7_1 {
            get {
                return ResourceManager.GetString("eventResult7-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string eventResult7_2 {
            get {
                return ResourceManager.GetString("eventResult7-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同学们还是发现了你身体的秘密，但你的盛世美颜深深折服了众人，你感到很自豪 的本地化字符串。
        /// </summary>
        internal static string eventResult8_0 {
            get {
                return ResourceManager.GetString("eventResult8-0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同学们还是发现了你身体的秘密，幸运的是大家接纳了你的不同，你的心中十分温暖 的本地化字符串。
        /// </summary>
        internal static string eventResult8_1 {
            get {
                return ResourceManager.GetString("eventResult8-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同学们还是发现了你身体的秘密，大家开始疏远你，你深刻意识到与他人的隔阂 的本地化字符串。
        /// </summary>
        internal static string eventResult8_2 {
            get {
                return ResourceManager.GetString("eventResult8-2", resourceCulture);
            }
        }
    }
}
